[package]
name = "process-fuzz"
version = "0.0.1"
edition = "2021"

[dependencies]
process = { path = ".." }
libfuzzer-sys = "0.4"

[[bin]]
name = "analyze_region"
path = "fuzz_targets/analyze_region.rs"

[workspace]
